modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com"

[[mods]]
modId="substractum"
version="0.0.1-alpha"
displayName="Substractum Necrosis"
authors="razchexlitiel"
description='''
    A dark, necrotic expansion for Minecraft.
    Master the forbidden arts and explore the substractum.
    '''
displayTest="MATCH_VERSION"

# Зависимость от Forge
[[dependencies.substractum]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

# Зависимость от самого Minecraft
[[dependencies.substractum]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Зависимость от GeckoLib (обязательно, раз мы его используем в коде)
[[dependencies.substractum]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="AFTER"
side="BOTH"
